apiVersion: oos.dev/v1alpha1
kind: Entity
metadata: { name: Employee, namespace: hr }
spec:
  nature: entity
  primaryKey: [employeeId]
  principal: true
  properties:
    employeeId: { type: String }
    nationalId:
      type: String
      labels: { gdpr.sensitivity: high }
