broker_endpoint = 'http://broker:50051'
pg_distrib_dir = '/usr/local/'
listen_pg_addr = '0.0.0.0:6400'
listen_http_addr = '0.0.0.0:9898'
remote_storage = { local_path = '/remote' }
control_plane_api = 'http://storcon:1234/upcall/v1/'
availability_zone = 'z1'
